version: '3.9'
services:

  rinha-api-1:
    image: openjdk:17-ea-5-jdk-alpine
    container_name: rinha-2023-api-1
    hostname: rinha-2023-api-1
    env_file:
      - .env.docker
    volumes:
      - ./target/rinha-2023-0.0.1-SNAPSHOT.jar:/rinha-2023-0.0.1-SNAPSHOT.jar
    ports:
      - '9991:9991'
    expose:
      - 9991
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - POSTGRES_DB_NAME=rinha
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgresql
      - SERVER_PORT=9991
      - OTHER_API_URL=http://rinha-2023-api-2:9992
      - KAFKA_CONSUMER_GROUP_ID=group-1
      - KAFKA_PRODUCER_TOPIC_PARTITION=0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    deploy:
      resources:
        limits:
          cpus: '0.41'
          memory: '896MB'
    networks:
      - rinha-network
    command: java -jar rinha-2023-0.0.1-SNAPSHOT.jar

  rinha-api-2:
    image: openjdk:17-ea-5-jdk-alpine
    container_name: rinha-2023-api-2
    hostname: rinha-2023-api-2
    volumes:
      - ./target/rinha-2023-0.0.1-SNAPSHOT.jar:/rinha-2023-0.0.1-SNAPSHOT.jar
    ports:
      - '9992:9992'
    expose:
      - 9992
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - POSTGRES_DB_NAME=rinha
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgresql
      - SERVER_PORT=9992
      - OTHER_API_URL=http://rinha-2023-api-1:9991
      - KAFKA_CONSUMER_GROUP_ID=group-1
      - KAFKA_PRODUCER_TOPIC_PARTITION=1
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    deploy:
      resources:
        limits:
          cpus: '0.41'
          memory: '896MB'
    networks:
      - rinha-network
    command: java -jar rinha-2023-0.0.1-SNAPSHOT.jar

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '512MB'

  postgresql:
    container_name: rinha-database
    image: postgres:14.10
    hostname: postgresql
    command: 'postgres -c max_connections=200 -c shared_buffers=512MB -c wal_buffers=64MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '896MB'
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  ## KAFKA AND ZOOKEEPER
#  zookeeper:
#    hostname: zookeeper
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    deploy:
#      resources:
#        limits:
#          cpus: '0.15'
#          memory: '128MB'
#    networks:
#      - rinha-network
#    ports:
#      - "22181:2181"

#  kafka:
#    hostname: kafka
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#    deploy:
#      resources:
#        limits:
#          cpus: '0.27'
#          memory: '384MB'
#    networks:
#      - rinha-network
#    healthcheck:
#      test: nc -z localhost 9092 || exit -1
#      start_period: 300s
#      interval: 60s
#      timeout: 300s
#      retries: 10
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  rinha-network: